In [29]:
import pandas as pd
import numpy as np
import os

In [30]:
tagged_words = pd.read_csv('tagged_words.csv')
tagged_words.head()

     word   tag
0     the   DET
1  fulton  NOUN
2  county  NOUN
3   grand   ADJ
4    jury  NOUN

In [31]:
# POS tag for each word based on rule/frequency from a sentence
# ignore case

def pos_tagging_sentence(sentence):
    # Split the sentence into words
    words = sentence.split()

    # Initialize an empty list to store the POS tags
    pos_tags = []

    # Iterate over each word in the sentence
    for word in words:
        # Convert the word to lowercase for case-insensitive matching
        word_lower = word.lower()

        # Check if the word is in the tagged_words DataFrame
        if word_lower in tagged_words['word'].values:
            # Get the corresponding POS tag from the DataFrame
            pos_tag = tagged_words.loc[tagged_words['word'] == word_lower, 'tag'].values[0]
            pos_tags.append(pos_tag)
        else:
            # If the word is not found, append 'NN' (noun) as a default tag
            pos_tags.append('NN')

    return pos_tags
pos_tagging_sentence('I saw him running away')

['PRON', 'VERB', 'PRON', 'VERB', 'ADV']

In [32]:
pos_tagging_sentence('He wished he was rich')

['PRON', 'VERB', 'PRON', 'VERB', 'ADJ']

In [33]:

emmission_matrix = pd.crosstab(tagged_words['word'],tagged_words['tag'],normalize='columns')

word = 'his'
emmission_matrix.loc[word][emmission_matrix.loc[word]>0].round(3)
emmission_matrix['PRON'].loc['his'].round(3)

0.001

In [34]:
transition_matrix(tagged_words).round(3)

,DET,NOUN,ADJ,VERB,ADP,ADV,CONJ,PRT,PRON,NUM,X
DET,0.006,0.627,0.253,0.065,0.009,0.018,0.001,0.002,0.010,0.010,0.001
NOUN,0.016,0.150,0.297,0.159,0.245,0.027,0.060,0.018,0.020,0.008,0.000
ADJ,0.097,0.323,0.173,0.066,0.103,0.054,0.070,0.028,0.070,0.014,0.001
VERB,0.163,0.098,0.138,0.184,0.169,0.103,0.014,0.066,0.055,0.009,0.000
ADP,0.456,0.258,0.092,0.041,0.020,0.016,0.002,0.014,0.070,0.030,0.000
ADV,0.074,0.033,0.307,0.240,0.142,0.097,0.017,0.029,0.048,0.013,0.000
CONJ,0.151,0.244,0.133,0.195,0.073,0.091,0.000,0.025,0.068,0.019,0.001
PRT,0.084,0.036,0.096,0.623,0.091,0.036,0.012,0.011,0.007,0.005,0.000
PRON,0.018,0.009,0.113,0.706,0.056,0.054,0.011,0.024,0.008,0.001,0.000
NUM,0.014,0.381,0.333,0.046,0.132,0.020,0.038,0.005,0.009,0.022,0.000
X,0.006,0.056,0.277,0.052,0.053,0.007,0.023,0.007,0.006,0.001,0.512